# Assignment - 3(3)

In [22]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
Buyer = pd.read_csv("https://excelr.s3.nl-ams.scw.cloud/DataScience-Assignments/Assignments/hypothesis%20Testing/BuyerRatio.csv")

In [24]:
Buyer

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [25]:
Buyer_table=Buyer.iloc[:,1:6]
Buyer_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [26]:
Buyer_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [27]:
val=stats.chi2_contingency(Buyer_table)

In [28]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [29]:
type(val)

tuple

In [30]:
Expected_value=val[3]

In [31]:
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [32]:
from scipy.stats import chi2

In [33]:
chi_square=sum([(o-e)**2/e for o,e in zip(Buyer_table.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [34]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [35]:
if chi_square_statestic >= critical_value:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)


In [36]:
pvalue=1-chi2.cdf(chi_square_statestic,3)

In [37]:
pvalue

0.6787446296467897

In [38]:
if pvalue <= 0.05:
	print('Dependent (reject H0)')
else:
	print('Independent (fail to reject H0)')

Independent (fail to reject H0)
